name: go-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: go-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ "20.8.0" ]
    steps:
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
        id: node

      - name: Check out code into the node directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: lint
        run: yarn lint

      - name: Test
        run: yarn test:coverage

  release:
    name: semantic-release
    runs-on: ubuntu-latest
    needs: [ build ]
    strategy:
      matrix:
        node: [ "20.8.0" ]
    steps:
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
        id: node

      - name: Check out code into the node directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.2
            @semantic-release/changelog@6.0.1
